### ISSUE TITLE
Please issue updates to this repo as releases

### ISSUE THREAD

**Issue by tehniemer** [tubearchivist/tubearchivist-plex#13]
Please use releases like you do with Tube Archivist. This will make it easier to know when updates have been made so users can pull the latest version and update their servers.

**Comment by lamusmaser** [comment]
Once we are satisfied with this being "stable", we will produce a v0.1.0 and onward to keep it in a similar framework. We are still making sure that it works for a small group of people first, then we will "officially" announce it as available and ready for use.

**Comment by tehniemer** [comment]
Great to hear
