### ISSUE TITLE
Forbidden on API Key link in readme

### ISSUE THREAD

**Issue by natewalck** [tubearchivist/tubearchivist-plex#14]
The API key reference links to https://docs.tubearchivist.com/settings/#integrations, which gives forbidden when one tries to access it.

**Comment by lamusmaser** [comment]
They just changed the docs list night after splitting the settings page. I'll update it with a new link when I'm at my computer later this morning. 

Meanwhile: https://docs.tubearchivist.com/settings/application/#integrations

**Comment by natewalck** [comment]
I found it in my settings page on my instance, but wanted to call out that the link was broken. Thanks for posting the updated link.
