### ISSUE TITLE
[Installation Help]: Most videos don't show in Plex, Metadata sync errors

### ISSUE THREAD

**Issue by micaharies** [tubearchivist/tubearchivist-plex#26]
### Installation instructions

- [X] I'm running the latest version of the TubeArchivist Plex Integration Scanner and Agent. I have read the latest release notes and installation instructions.

### Operating System

Ubuntu Server, docker

### Your installation or setup question

Hi! I'm having issues getting Plex and TA to play nice. I have around 1500~ videos archived right now, but only 4 channels show up with less than 20 videos for each. The plugin is throwing an error as well. I'm assuming I did something wrong during setup of either TA or this plugin but I haven't been able to track down exactly what is wrong. When I use the docker internal IP for the ta_config.json file and plex library, it throws the 111 error. when I use the reverse proxy URL it 403s. When I use the host IP, it 400s. Maybe a docker network issue? 

Any help would be massively appreciated!
Thanks!!

### Relevant log output

```Shell
URLError: <urlopen error [Errno 111] Connection refused>

Error in Python: Running scanner:

Traceback (most recent call last):

  File "/config/Library/Application Support/Plex Media Server/Scanners/Series/TubeArchivist Series Scanner.py", line 314, in Scan

    TA_CONFIG['online'], TA_CONFIG['version'] = test_ta_connection()

  File "/config/Library/Application Support/Plex Media Server/Scanners/Series/TubeArchivist Series Scanner.py", line 222, in test_ta_connection

    raise e



HTTPError: HTTP Error 403: Forbidden

Error in Python: Running scanner:

Traceback (most recent call last):

  File "/config/Library/Application Support/Plex Media Server/Scanners/Series/TubeArchivist Series Scanner.py", line 314, in Scan

    TA_CONFIG['online'], TA_CONFIG['version'] = test_ta_connection()

  File "/config/Library/Application Support/Plex Media Server/Scanners/Series/TubeArchivist Series Scanner.py", line 222, in test_ta_connection

    raise e


HTTPError: HTTP Error 400: Bad Request

Error in Python: Running scanner:

Traceback (most recent call last):

  File "/config/Library/Application Support/Plex Media Server/Scanners/Series/TubeArchivist Series Scanner.py", line 314, in Scan

    TA_CONFIG['online'], TA_CONFIG['version'] = test_ta_connection()

  File "/config/Library/Application Support/Plex Media Server/Scanners/Series/TubeArchivist Series Scanner.py", line 222, in test_ta_connection

    raise e
```

**Comment by lamusmaser** [comment]
There is currently an issue where the Agent cannot handle IP addresses as part of the request. Beyond this, we would have expected that the reverse proxy should have gone through, so I would ask if you can reach out to that same URL in a browser what kind of response you get.

Docker internal IP would only work if they are on the same Docker network, but also see issue 1, where IP addresses are currently not able to be handled.

**Comment by micaharies** [comment]
![signal-2023-11-09-144155_004](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/30b7efe7-183a-4b96-a3d7-e707f1ca955c)
![signal-2023-11-09-144155_003](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/b9d4af2b-0d82-4897-83e0-150cd993e181)
![signal-2023-11-09-144155_002](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/af169127-0d41-46bf-ad5c-d9e88a611ff1)
![screenshot_204](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/ad3b132a-53a0-4307-b276-063352ec6ebe)

from what I can tell it still seems to be broken even with the proper URL

**Comment by lamusmaser** [comment]
Looks like the log snippet is not showing the full set. Can you include a more complete log response, at the very least from the "Attempting to connecting to TubeArchivist..." statement forward? I think there are details that are being missed based on that section of code.

Just as a quick check, as well, can you also provide the permissions of the `ta_config.json` file?

**Comment by micaharies** [comment]
Not seeing the "Attempting to connecting to TubeArchivist..." part in Plex logs at all. 
![screenshot_205](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/06e489e9-9fce-43de-a491-4d3c936070a5)
Perms for the ta_config file are the same as Plex

**Comment by lamusmaser** [comment]
OK, can we review the full logs, then? There is definitely something still missing that isn't allowing me to troubleshoot this fully.

**Comment by micaharies** [comment]
this is what shows after a reboot and scanning the folder
![screenshot_206](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/431b41fa-45fa-4da9-b860-a5eed104f93b)

**Comment by lamusmaser** [comment]
Gotcha. Can we get the logs from `/config/Library/Application Support/Plex Media Server/Logs/TubeArchivist Scanner/_root_.scanner.log` from within the container? This should be the location of the Scanner's logs based on the details presented.

**Comment by micaharies** [comment]
![screenshot_207](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/893b06d0-75e8-493f-a67b-b0d5276b855b)

**Comment by lamusmaser** [comment]
Just running through that section again manually, it does look like it instantiates the Request object, which is then passed on to the `read_url` function, and that should be able to make the request using the header that supplies the Authorization Token. So, what we need to determine is why it is running differently for you and passing back a Forbidden response. Additionally, I need to look into why it isn't handling that response.

Based on the earlier images, it looks like the API key is expected to be the same between the two, but please just validate that all of the characters are the same, again. 

Next steps would be attempting to make the same connection attempt from within the Plex container and see if it is getting stuck from there.

If you want to try that, I would attempt to make a curl request from the Plex container to the reverse proxy URL you are trying to reach. Let me know if you need help formatting a fully request.

**Comment by micaharies** [comment]
I just double checked that those are the correct API keys and they are. I probably do need help with the curl request, honestly not super familiar with all that

**Comment by lamusmaser** [comment]
You can utilize it following the following format:
```curl -L -H "Authorization: Token XXXXXXXXXXXXXXXXXXXXXXXXXXX" https://subdomain.example.com/api/ping```

Let's just walk through each of these, more details found [here](https://linux.die.net/man/1/curl).
`-L` is for `Location`, which follows a redirection. Many reverse proxies enforce a redirection of some kind. This follows their recommendation for where to go with that request.
`-H` is for `Headers`, which allows custom headers to be included. We are only providing the `Authorization` header, along with the token. You only need to replace the XXXXXXXXXXXXXXXXXXXXXXXXXXX` section with your API key.
Finally, the end is the full URL that you are pointing to. We are, as you know from your request earlier, pointing to the `/api/ping` endpoint.

This should allow it to request the JSON response. If curl does not exist on the Plex container, let me know and I'll get a copy of the container to determine next steps.

**Comment by micaharies** [comment]
![screenshot_385](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/691f7026-0f92-4b48-9d5d-f55aca2282f5)
thanks for the explanation! this is what it returned with

**Comment by lamusmaser** [comment]
In terms of what we were expecting, that's great! It means that the connection is working as expected and the Plex container can reach out to the TubeArchivist endpoint successfully. What it also means is that there is some other reason why it is getting a 403 error, and I'm not sure why that is occurring, but it could be several things. Let me look into it more and I'll get back to you about what we can do for a next step.

In the meantime, could you follow these instructions and let's rule out an issue from the Plex Token? I might need to add those instructions back in if this does work:

Setup the [`X-Plex-Token` file](https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token). This should be a file in the `Plex Media Server` directory, so the file would be `/config/Library/Application Support/Plex Media Server/X-Plex-Token` for your configuration.

**Comment by micaharies** [comment]
I am aware of how to find the token with the XML file but I don't see a file anywhere in that folder. Is it just supposed to be a text file with the token or something like that?

**Comment by lamusmaser** [comment]
You have to create the file if it doesn't exist.

Let me know if generating that and restarting Plex starts working. If not, I'll finish my code review and figure out what else might be potentially causing this issue.

**Comment by micaharies** [comment]
![screenshot_389](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/ac14828e-1cf6-4824-813b-32c61faf4b97)

sorry, is this supposed to be a text file with the X-Plex-Token in it? There is no file in the directory. How do I generate this? That Plex article didnt really say anything about generating a file.

**Comment by lamusmaser** [comment]
Correct. So, the easiest way would be to create the file and add the token inside.

Something like:
```
vi X-Plex-Token
<i>
<paste>
<esc>
<:wq!>
```
In order, that would open the file in the text editor, `vi`, then sends it to `Insert Mode`. Paste in the token value by itself, no changes, then hit the `escape` key to exit `Insert Mode`. Finally, the last set of characters will save and exit `vi`. I can provide instructions for other Linux text editors if you feel more comfortable in another one or `vi` is not available on your system.

**Comment by micaharies** [comment]
![screenshot_391](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/5f449c9d-7ce8-4b67-9f10-e45756bb2a0a)
went ahead and generated that and restarted the container and I'm still getting this error in the scanner logs

**Comment by lamusmaser** [comment]
OK, thank you for testing that. Just wanted to see if that was causing it.

I'll draft up a next step for troubleshooting, which will probably be Python-based, to see what is causing it. Give me some time - I'm focused on another task at the moment and I will probably run out of time today to get to drafting that here.

**Comment by micaharies** [comment]
No worries, thank you so much!! I really appreciate the help so far

**Comment by lamusmaser** [comment]
Alright, on the system that is hosting Plex, start a python2.7 console. Running `python2` should get you into the IDE (confirm it is running the Python 2 version in the preamble). Once there, run through the following steps, one line at a time. I will only need the response at the end and any associated errors. I went through these exact steps on my Plex hosting system, so they should be similar.

```
import json, ssl
from urllib2 import urlopen, Request
from ssl import PROTOCOL_SSLv23 as SSL_PROTOCOL

SSL_CONTEXT       = ssl.SSLContext(SSL_PROTOCOL)

TA_CONFIG = {}
TA_CONFIG['ta_url'] = "<InsertHere>"
TA_CONFIG['ta_api_key'] = "<InsertHere>"

request_url = Request("{}/api/ping".format(TA_CONFIG['ta_url']), headers={"Authorization": "Token {}".format(TA_CONFIG['ta_api_key'])})
url_content = urlopen(request_url,context=SSL_CONTEXT).read()
response = json.loads(url_content)
print(response)
```

I would expect it to be similar to mine:
```
>>> print(response)
{u'version': [0, 4, 2], u'response': u'pong', u'user': 1}
```

**Comment by micaharies** [comment]
![screenshot_392](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/9a69e54f-6489-40d2-b0f0-2a5b495cd967)
I keep getting this when I run the `url_content` part, is it supposed to include the https part of the URL?

**Comment by lamusmaser** [comment]
Ah, yes, I should have specified. Try it again as `https://tube.mhaire.net`.

**Comment by micaharies** [comment]
![screenshot_395](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/6b9327fb-c571-45a5-8a32-b9a0864347a6)
still seems to be doing it

**Comment by lamusmaser** [comment]
Oh, I see it. Remove the `<` and `>` around the URL. That will help it out.

**Comment by micaharies** [comment]
![screenshot_398](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/5b412ac2-9324-49cd-b8bf-c27a4da88380)
sorry about that, this is where I'm at now

**Comment by micaharies** [comment]
![screenshot_208](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/33c5b0b2-7249-4ea2-b0ed-c61eacff994d)
This is what I got, same error I believe

**Comment by lamusmaser** [comment]
Which reverse proxy do you have in front of this? I am able to fully replicate those steps and it comes back with a 200 Response, so it would either have to be the application rejecting it (which we can verify from the TubeArchivist logs) or the proxy rejecting it or some aspect of the response (in which I need more details to understand which details I need to look for).

**Comment by micaharies** [comment]
I'm using Apache, would there be logs somewhere I could check to see if that's the problem?

**Comment by lamusmaser** [comment]
There might be some in the Apache logs, but results for `mod_proxy` are limited when discussing logs. By default, it seems they would be in either `/var/log/apache2` or `/var/log/httpd`. Alternatively, do you have `Order` operator? If so, do you have it set to `Order allow, deny` or `Order deny, allow`? Additionally, do you have an `Allow` operator, and is the Plex host configured to be allowed access?

**Comment by lamusmaser** [comment]
Can I review the configuration that you have for the TA proxy?

**Comment by micaharies** [comment]
![screenshot_209](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/6c51fba7-fa86-4c5b-a424-c8105a186fd4)
this is what i've got, basically everything I use that's reverse proxied is effectively the same thing with ports and URL changed

**Comment by lamusmaser** [comment]
This does look like it is a good configuration that shouldn't be overzealous. Do you have a `mod_security` module that is in use somewhere? That's the only thing that I can see.

Beyond this, I would say that we should do some testing from the TA side and see if that is where the 403 is being thrown from.

**Comment by micaharies** [comment]
![screenshot_210](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/f30f81c0-9e2a-40a2-87d4-ad9d94bd6a12)
I don't have mod security, though now that I think about it I do run everything proxied behind CloudFlare. Any chance that would be an issue?

**Comment by lamusmaser** [comment]
Oh, that could be it. Does CloudFlare have any restrictions on hosts that can access the site?

**Comment by micaharies** [comment]
I don't believe so? Honestly I haven't had a problem like this before, even with 40+ docker containers currently installed with tons of internet facing websites and systems. I can turn proxy off and try again and see what happens

**Comment by micaharies** [comment]
![image](https://github.com/tubearchivist/tubearchivist-plex/assets/77802123/d5022aa4-501f-4e0d-af7e-4ac93931e2aa)
I opened Plex this morning and it appears it's working! I guess the CloudFlare proxy did break it. Never would've guessed that was the problem. Thank you so much for your help, it's super appreciated!!
