### ISSUE TITLE
[Feature Request]: Make video duration info more visible

### ISSUE THREAD

**Issue by V4ler1an** [tubearchivist/tubearchivist-plex#56]
### I've read the documentation.

- [X] I have read the [current limitations](https://github.com/tubearchivist/tubearchivist-plex#limitations), and confirmed that this hasn't been requested as a [feature request](https://github.com/tubearchivist/tubearchivist-plex/issues?q=is%3Aissue) previously.

## Is your feature request related to a problem? Please describe.
In YouTube's official web or Android TV UI, the video length is overlayed on each thumbnail so the information is always on display. This is important for the user experience, enabling you to select a video you have enough time to watch. The TA Plex library UI only displays video length in certain screens or when a specific 'Duration' based view filter is applied.

## Describe the solution you'd like
It would be a great help if video duration metadata could be included as standard beneath all videos, regardless of the view filter in use.

## Additional context
![image](https://github.com/tubearchivist/tubearchivist-plex/assets/134781183/0857515f-e984-43c2-8c93-6d260faa3e1d)
![image](https://github.com/tubearchivist/tubearchivist-plex/assets/134781183/28b51f14-84d0-4b0d-acad-3b8590851ba0)

### Your help is needed!

- [ ] Yes, I will work on this in the next few days or weeks.

**Comment by lamusmaser** [comment]
There is only so much that I can change, but I will see if I can add some additional details. There are some other things that are hard to read from mobile/alternate sources that could be added to the description of the videos. This will duplicate some of the data, but I think that this can be beneficial for several use cases.

**Comment by V4ler1an** [comment]
Thanks @lamusmaser.

**Comment by lamusmaser** [comment]
I don't think I can modify the filter/sorting results, but I can add some additional details to the top of the Description. My plan was to update it to be the following:

```
Runtime: {XX} min
YTID: {XXXXXXXXX}
Title: {metadata.title}
{description}
```

What this should do is add a few more pieces of information that can be seen in the overviews of most areas. That should decrease number of clicks. Additionally, for those instances where the YouTube video's title is too longer for Plex to show it, this will allow someone to see what the full title is within the description. We'll keep the YTID in there to have a reference (and show that this piece is working.)

**Comment by lamusmaser** [comment]
Incorporated into v0.1.5. This will now show as presented for videos. I won't be able to handle the other areas, but this should help in a lot of places.

**Comment by lamusmaser** [comment]
Here is what I see now: 
![Screenshot_20240513_114307_Plex](https://github.com/tubearchivist/tubearchivist-plex/assets/1940060/1f165069-f9f0-4f3a-8cff-94493d3619e0)

**Comment by V4ler1an** [comment]
This looks helpful, i'll try and update and take a look at the new version soon.

**Comment by lamusmaser** [comment]
v0.1.5 is now released and available. Closing until someone reports this as a continued issue.
