### ISSUE TITLE
[Bug]: Channel posters missing

### ISSUE THREAD

**Issue by filmkorn** [tubearchivist/tubearchivist-plex#71]
### I've read the documentation.

- [X] I'm running the latest version of the TubeArchivist Plex Integration Scanner and Agent. I have read the latest release notes and installation instructions.

### Operating System

Linux

## Describe the bug

The screenshot of the Readme shows channel art displayed yet I'm unable to make this work. Unsure if this is supported?

I've carefully followed the installation instructions and also tried the docker mod as is very convenient.

The log in `library/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.tubearchivist_agent.log` only show this Error only once (after fixing #67):

```
ERROR (networking:197) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
```

The logs never show `[X] Posters` for any banners, art uploaded (only for thumbs).

Apologies if I missed something!

## Steps To Reproduce

Add a new channel to TA.
Rescan library or Refresh metadata.

## Expected behaviour

Channels have posters / thumbnails.

### Relevant log output

```Shell
$ cat com.plexapp.agents.tubearchivist_agent.log | grep UC2C_jShtL725hvbm1arSV9w

2024-06-12 11:48:15,645 (7f9b9d1b08) :  DEBUG (model:32) - Loading model with GUID com.plexapp.agents.tubearchivist_agent://tubearchivist|UC2C_jShtL725hvbm1arSV9w|UC2C_jShtL725hvbm1arSV9w?lang=en
2024-06-12 11:48:15,869 (7f9b9d1b08) :  INFO (__init__:366) - Attempting to connect to TubeArchivist to lookup YouTube channel: UC2C_jShtL725hvbm1arSV9w
2024-06-12 11:48:15,958 (7f9b9d1b08) :  INFO (__init__:467) - Response from TubeArchivist received for YouTube channel: UC2C_jShtL725hvbm1arSV9w
2024-06-12 11:48:15,960 (7f9b9d1b08) :  INFO (__init__:946) - [_] Posters: 20240611_/cache/channels/UC2C_jShtL725hvbm1arSV9w_thumb.jpg
2024-06-12 11:48:15,962 (7f9b9d1b08) :  INFO (__init__:820) - [_] Art: 20240611_/cache/channels/UC2C_jShtL725hvbm1arSV9w_tvart.jpg
2024-06-12 11:48:15,965 (7f9b9d1b08) :  INFO (__init__:849) - [_] Banners: 20240611_/cache/channels/UC2C_jShtL725hvbm1arSV9w_banner.jpg
```

**Comment by lamusmaser** [comment]
It looks like an issue from the Plex Server side, where it is having problems with accessing the specific resource via its API. But the posters themselves have been added and processed (`X` shows the first time it is processed;  `_` shows if it was previously processed and is in the Object's lost of images).

You could do the Plex Dance and see if that clears things for you.

**Comment by filmkorn** [comment]
I can tell that this is an issue with my plex installation.

Upon adding a new channel I can now find a `[X] Posters` log

```
INFO (__init__:949) - [X] Posters: 20240613_/cache/channels/UCDyZXmOevDAb6DHyUCwzVNg_thumb.jpg
```

I can find the posters in : `library/Library/Application Support/Plex Media Server/Metadata/TV Shows/#/#######################################.bundle/Contents/com.plexapp.agents.tubearchivist_agent/posters`

Meaning this integration is able to pull them from TA.

I suspect Plex would be symlinking the art into either `_stored` or `_combined` folders (I cannot tell as the filesystem I'm currently using doesn't support symlinks).

Thanks for the quick response and your work on this integration!
Closing

**Comment by folofjc** [comment]
@filmkorn How did you fix this on your plex side?

**Comment by filmkorn** [comment]
I converted the drive I was using from exFAT (no support for symlinks) to ext4 (backing up enverything, formatting with `mkfs.ext4` and restoring everything). Can confirm the file system must support symlinks for thumbnails to work.

```
ls -al /library/Library/Application\ Support/Plex\ Media\ Server/Metadata/TV\ Shows/3/a30d46fe766e19b8c531ebc3714fdde3703773e.bundle/Contents/_combined/posters/com.plexapp.agents.tubearchivist_agent_0e02b5d8f382b67c038af0bd58cd55a3e6fc510f
lrwxrwxrwx 1 pi pi 101 Jun 16 23:38 '/library/Library/Application Support/Plex Media Server/Metadata/TV Shows/3/a30d46fe766e19b8c531ebc3714fdde3703773e.bundle/Contents/_combined/posters/com.plexapp.agents.tubearchivist_agent_0e02b5d8f382b67c038af0bd58cd55a3e6fc510f' -> ../../_stored/posters/com.plexapp.agents.tubearchivist_agent_0e02b5d8f382b67c038af0bd58cd55a3e6fc510f
```

As you can see the posters are symlinked.
